eastern africa countries and libya
hilory16/african-states-and-tribes pull request #11
Opened 2024-08-26 23:03 UTC by fadaco

east african countries for kenya, tanzania, libya, burundi and rwanda

2024-08-26 23:58 UTC, hilory16 requested changes

2024-08-26 23:58 UTC, hilory16 commented on src/data/africa/tribes/BF.json
Some properties are missing.
This is the expected format:


            "capitalCity":"", // capital city
            "geoPoliticalZone"",  // This can be black
            "location":"South East", // Preferrable in this format South East, North East (Central is acceptable)
            "name": "", // name of the state, region or province
            "stateCode": "AB",
            "tribes":[""],
            "type": "" //state or region or province, etc.

2024-08-26 23:58 UTC, hilory16 commented on src/data/africa/tribes/BF.json
The JSON key should be UPPERCASE
e.g

"BUBANZA" :{
...
},

"BUJUMBURA MAIRIE":{
...
}

2024-08-27 00:56 UTC, fadaco commented on src/data/africa/tribes/BF.json
fixed

2024-10-22 11:20 UTC, merged